# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - config-server-ecalderc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ee93c6a9938a4c03aa2ff3bddf8ba522 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b0e4e4bdb520460ca6803a42dbd5618e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ee93c6a9938a4c03aa2ff3bddf8ba522 }}/config-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'config-server-ecalderc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bc76073467a14282a9863ae2f9cb8f5f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ee93c6a9938a4c03aa2ff3bddf8ba522 }}/config-server:${{ github.sha }}'